apiVersion: v1
kind: Pod
metadata:
  name: hello-client
  labels:
    app: hello-app
spec:
  containers:
  - name: hello-client
    image: registry.ocp4.example.com:8443/redhattraining/podman-hello-client
