apiVersion: v1
kind: Pod
metadata:
  name: hello-server
  labels:
    app: hello-app
    run: hello-server
spec:
  containers:
  - name: hello-server
    image: registry.ocp4.example.com:8443/redhattraining/podman-hello-server
    ports:
    - containerPort: 3000
