apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea-postgres
  name: gitea-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgres
  template:
    metadata:
      labels:
        app: gitea-postgres
    spec:
      containers:
      - image: registry.ocp4.example.com:8443/rhel9/postgresql-13:1
        name: postgresql-13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRESQL_USER
          value: gitea
        - name: POSTGRESQL_PASSWORD
          value: gitea
        - name: POSTGRESQL_DATABASE
          value: gitea